// AUTO-GENERATED by prisma/scripts/extract-lot-ev.ts — DO NOT EDIT.
// Re-run the extractor after refreshing /tmp/c3d_api.json.
// Source: concept3d map 1314 (CSULB), catIds 41613 + 77326.

export type EvPresence = {
  lot_id: string;
  concept3d_marker_ids: number[];
  concept3d_marker_names: string[];
};

export const LOT_EV_PRESENCE: Record<string, EvPresence> = {
  "E8": {
    lot_id: "E8",
    concept3d_marker_ids: [895456,895457],
    concept3d_marker_names: ["Lot E8 EV Charging"],
  },
  "G12": {
    lot_id: "G12",
    concept3d_marker_ids: [1115730,1115731],
    concept3d_marker_names: ["Lot G12 EV Charging"],
  },
  "G7": {
    lot_id: "G7",
    concept3d_marker_ids: [413915,533706,876715,876716],
    concept3d_marker_names: ["Lot G7 EV Charging","Lot G7 EV Charger Location"],
  },
  "PVS": {
    lot_id: "PVS",
    concept3d_marker_ids: [414936,876718],
    concept3d_marker_names: ["Palo Verde South EV Charging"],
  },
  "PYR": {
    lot_id: "PYR",
    concept3d_marker_ids: [413916,876719],
    concept3d_marker_names: ["Pyramid Parking Structure EV Charging"],
  },
  "R2": {
    lot_id: "R2",
    concept3d_marker_ids: [575361,876717],
    concept3d_marker_names: ["Lot R2 EV Charger Locations"],
  },
};
