/**
 * Dev-time generator: read /tmp/c3d_api.json, run the shared extractor
 * against the committed LOT_GEOFENCES, and emit prisma/lot-advisories.generated.ts
 * for the seeders.
 *
 * Production refresh is handled by the weekly cron at
 * src/scheduler/jobs/refresh-lot-advisories.job.ts which writes the same advisories
 * directly to the lot_advisories table.
 *
 * Run: pnpm exec ts-node --project tsconfig.scripts.json \
 *        prisma/scripts/extract-lot-advisories.ts
 */
import * as fs from 'fs';
import * as path from 'path';

import { LOT_GEOFENCES } from '../lot-geofences.generated';
import {
  extractLotAdvisories,
  type C3DLocation,
  type LotPolygon,
} from '../../src/lots/lot-advisory-extractor';

const CONCEPT3D_CACHE = process.env.CONCEPT3D_CACHE_PATH ?? '/tmp/c3d_api.json';
const OUTPUT_PATH = path.join(__dirname, '..', 'lot-advisories.generated.ts');

function main(): void {
  if (!fs.existsSync(CONCEPT3D_CACHE)) {
    throw new Error(
      `Concept3d cache not found at ${CONCEPT3D_CACHE}. ` +
        `Set CONCEPT3D_CACHE_PATH or refresh the cache first.`,
    );
  }
  const items = JSON.parse(fs.readFileSync(CONCEPT3D_CACHE, 'utf8')) as C3DLocation[];
  const lots: LotPolygon[] = Object.entries(LOT_GEOFENCES).map(([lot_id, g]) => ({
    lot_id,
    polygon: g.polygon,
  }));

  const { seeds, stats } = extractLotAdvisories(items, lots);

  console.log(
    `[advisories] ${stats.candidateCount} concept3d entries across cats ` +
      `45989,91209,91668,101030`,
  );
  console.log(
    `[advisories] produced ${seeds.length} (lot,advisory) pairs from ` +
      `${stats.markerCount} markers`,
  );
  if (stats.polylineSkipped) {
    console.log(
      `[advisories] ${stats.polylineSkipped} non-polygon entries skipped ` +
        `(polylines/markers with no lot name mention)`,
    );
  }
  if (stats.unmatched) {
    console.log(
      `[advisories] ${stats.unmatched} polygon advisories did not overlap any lot ` +
        `(off-lot construction — informational only, not seeded)`,
    );
  }

  const byLot = seeds.reduce<Record<string, typeof seeds>>((acc, s) => {
    (acc[s.lot_id] ??= []).push(s);
    return acc;
  }, {});
  console.log('\n[advisories] per-lot summary:');
  for (const lotId of Object.keys(byLot).sort()) {
    const list = byLot[lotId];
    console.log(`  ${lotId.padEnd(4)} ${list.length} advisory(ies)`);
    for (const s of list) {
      console.log(`    - [${s.severity}] (${s.match_reason}) ${s.title}`);
    }
  }

  const banner = `// AUTO-GENERATED by prisma/scripts/extract-lot-advisories.ts — DO NOT EDIT.
// Re-run the extractor after refreshing /tmp/c3d_api.json.
// Source: concept3d map 1314 (CSULB).

import type { LatLng } from './lot-geofences.generated';

export type AdvisorySeed = {
  lot_id: string;
  title: string;
  description: string | null;
  severity: 'INFO' | 'ADVISORY' | 'CLOSURE';
  source: 'CONCEPT3D';
  source_cat_id: number;
  source_marker_id: number;
  match_reason: 'name_mention' | 'polygon_overlap';
  polygon: LatLng[];
};

export const LOT_ADVISORIES: AdvisorySeed[] = ${JSON.stringify(seeds, null, 2)};
`;
  fs.writeFileSync(OUTPUT_PATH, banner, 'utf8');
  console.log(`\n[advisories] wrote ${OUTPUT_PATH}`);
}

main();
